services:

  mongo:
    image: mongo
    container_name: fso-todo-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: fso-todo
    volumes: 
      - mongo_data:/data/db
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  redis:
    image: redis:7-alpine
    container_name: fso-todo-redis
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data

  backend:
    build:
      context: ./todo-backend
      dockerfile: Dockerfile
    container_name: todo-backend-prod
    environment:
      - REDIS_URL=redis://redis:6379
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/fso-todo
    depends_on:
      - mongo
      - redis

  frontend:
    build:
      context: ./todo-frontend
      dockerfile: Dockerfile
      args:
        VITE_BACKEND_URL: /api
    container_name: todo-frontend-prod

  nginx:
    image: nginx:1.20.1
    container_name: reverse-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - backend
      - frontend

volumes:
  mongo_data:
  redis_data: