# fly.toml app configuration file generated for full-stack-open-pokedex-patient-log-4812 on 2025-08-16T23:39:10+04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fso-11-pokedex'
primary_region = 'fra'

[env]
  PORT = "3000"

[processes]
  app = "node app.js"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    method = "GET"
    path = "/health"

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1

[deploy]
  strategy = "canary"

