services:
  db:
    image: postgres:17-bookworm
    container_name: fso13-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: blog
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d blog"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: ./backend-sql
      dockerfile: dev.Dockerfile
    container_name: fso13-backend-sql
    environment:
      DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@db:5432/blog
      PORT: 3001
    ports:
      - "3001:3001"
    volumes:
      - ./backend-sql:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
