name: CI/CD Pipeline for front-end part of Part 7 of FSO Course - Project BlogApp

on:
  push:
    branches: [main, part-11/task-11.20/optimize-ci-cd]
    paths:
      - 'Part-7/blog/frontend/blog_redux/**'
      - 'Part-7/blog/frontend/blog_query/**'
  pull_request:
    branches: [main]
    paths:
      - 'Part-7/blog/frontend/blog_redux/**'
      - 'Part-7/blog/frontend/blog_query/**'
  workflow_dispatch:

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      blog_redux: ${{ steps.filter.outputs.blog_redux }}
      blog_query: ${{ steps.filter.outputs.blog_query }}
      audit_redux: ${{ steps.filter.outputs.audit_redux }}
      audit_query: ${{ steps.filter.outputs.audit_query }}
    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            blog_redux:
              - 'Part-7/blog/frontend/blog_redux/**'
            audit_redux:
              - 'Part-7/blog/frontend/blog_redux/package.json'
              - 'Part-7/blog/frontend/blog_redux/package-lock.json'

            blog_query:
              - 'Part-7/blog/frontend/blog_query/**'
            audit_query:
              - 'Part-7/blog/frontend/blog_query/package.json'
              - 'Part-7/blog/frontend/blog_query/package-lock.json'

  # -------------------------
  # Redux app
  # -------------------------
  ci-blog_redux:
    needs: changes
    if: needs.changes.outputs.blog_redux == 'true'
    name: Frontend CI - blog_redux
    uses: ./.github/workflows/reusable-frontend-ci.yml
    with:
      app_slug: blog_redux
      working_directory: Part-7/blog/frontend/blog_redux
      backend_directory: Part-7/blog/backend
      backend_node_version: '22'
      backend_port: 3003
      backend_health_path: /health
      backend_timeout_ms: 120000
      frontend_node_version: '22'
      e2e_library: playwright
      frontend_port: 5173
      frontend_url: 'http://127.0.0.1:5173'
      frontend_timeout_ms: 120000
      e2e_artifact_paths: |
        Part-7/blog/frontend/blog_redux/playwright-report/**
        Part-7/blog/frontend/blog_redux/test-results/**
      audit-needed: ${{ needs.changes.outputs.audit_redux }}
    secrets:
      TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI_REDUX }}

  prod-build-redux:
    needs: ci-blog_redux
    if: needs.ci-blog_redux.outputs.should_deploy == 'true'
    uses: ./.github/workflows/reusable-frontend-prod-build.yml
    with:
      app_slug: blog_redux
      working_directory: Part-7/blog/frontend/blog_redux
      frontend_node_version: '22'
      prod_api_url: https://blogs-fso.fly.dev
      extra_files: vercel.json

  tag-generate-redux:
    needs: prod-build-redux
    if: needs.prod-build-redux.result == 'success'
    uses: ./.github/workflows/reusable-tag-generate.yml
    with:
      tag-prefix: blogapp-redux-

  vercel-deploy-redux:
    needs: [prod-build-redux, tag-generate-redux]
    if: needs.prod-build-redux.result == 'success' && needs['tag-generate-redux'].result == 'success'
    uses: ./.github/workflows/reusable-vercel-deploy.yml
    with:
      artifact-name: ${{ needs.prod-build-redux.outputs.artifact_name }}
      image-label: ${{ needs['tag-generate-redux'].outputs.new_tag }}
    secrets:
      FSO_VERCEL_TOKEN: ${{ secrets.FSO_VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      # VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_REDUX }}
      VERCEL_PROJECT_ID: 'prj_6XKuTqUP8rcBnr41JApKSyF8ngxA'

  tag-push-redux:
    needs: [vercel-deploy-redux, tag-generate-redux]
    if: >
      needs['vercel-deploy-redux'].result == 'success' &&
      needs['tag-generate-redux'].result == 'success' &&
      needs['tag-generate-redux'].outputs.new_tag != ''
    permissions:
      contents: write
    uses: ./.github/workflows/reusable-tag-push.yml
    with:
      tag-to-push: ${{ needs['tag-generate-redux'].outputs.new_tag }}

  notify-redux:
    if: ${{ always() }}
    needs: [ci-blog_redux, prod-build-redux, tag-generate-redux, vercel-deploy-redux, tag-push-redux]
    uses: ./.github/workflows/reusable-telegram-deploy-notify.yml
    with:
      project-name: 'FSO BlogApp Frontend (React + Redux + Tailwind CSS)'
      should-deploy: ${{ needs.ci-blog_redux.outputs.should_deploy }}
      new-tag: ${{ needs['tag-generate-redux'].outputs.new_tag }}
      statuses-text: |
        Job statuses:
        • CI-checks:     ${{ needs.ci-blog_redux.result }}
        • Prod build:    ${{ needs['prod-build-redux'].result }}
        • Tag-generate:  ${{ needs['tag-generate-redux'].result }}
        • Vercel deploy: ${{ needs['vercel-deploy-redux'].result }}
        • Tag-push:      ${{ needs['tag-push-redux'].result }}
    secrets:
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}

  # -------------------------
  # Query app
  # -------------------------
  ci-blog_query:
    needs: changes
    if: needs.changes.outputs.blog_query == 'true'
    name: Frontend CI - blog_query
    uses: ./.github/workflows/reusable-frontend-ci.yml
    with:
      app_slug: blog_query
      working_directory: Part-7/blog/frontend/blog_query
      backend_directory: Part-7/blog/backend
      backend_node_version: '22'
      backend_port: 3003
      backend_health_path: /health
      backend_timeout_ms: 120000
      frontend_node_version: '20'
      e2e_library: cypress
      frontend_port: 5173
      frontend_url: 'http://127.0.0.1:5173'
      frontend_timeout_ms: 120000
      e2e_artifact_paths: |
        Part-7/blog/frontend/blog_query/cypress/reports/**
        Part-7/blog/frontend/blog_query/cypress/screenshots/**
        Part-7/blog/frontend/blog_query/cypress/videos/**
      audit-needed: ${{ needs.changes.outputs.audit_query }}
    secrets:
      TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI_QUERY }}

  prod-build-query:
    needs: ci-blog_query
    if: needs.ci-blog_query.outputs.should_deploy == 'true'
    uses: ./.github/workflows/reusable-frontend-prod-build.yml
    with:
      app_slug: blog_query
      working_directory: Part-7/blog/frontend/blog_query
      frontend_node_version: '22'
      prod_api_url: https://blogs-fso.fly.dev
      extra_files: vercel.json

  tag-generate-query:
    needs: prod-build-query
    if: needs.prod-build-query.result == 'success'
    uses: ./.github/workflows/reusable-tag-generate.yml
    with:
      tag-prefix: blogapp-query-

  vercel-deploy-query:
    needs: [prod-build-query, tag-generate-query]
    if: needs.prod-build-query.result == 'success' && needs['tag-generate-query'].result == 'success'
    uses: ./.github/workflows/reusable-vercel-deploy.yml
    with:
      artifact-name: ${{ needs.prod-build-query.outputs.artifact_name }}
      image-label: ${{ needs['tag-generate-query'].outputs.new_tag }}
    secrets:
      FSO_VERCEL_TOKEN: ${{ secrets.FSO_VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      # VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_QUERY }}
      VERCEL_PROJECT_ID: 'prj_9bFR1EaMi0KqD54nxHnonOxGAzGb'

  tag-push-query:
    needs: [vercel-deploy-query, tag-generate-query]
    if: >
      needs['vercel-deploy-query'].result == 'success' &&
      needs['tag-generate-query'].result == 'success' &&
      needs['tag-generate-query'].outputs.new_tag != ''
    permissions:
      contents: write
    uses: ./.github/workflows/reusable-tag-push.yml
    with:
      tag-to-push: ${{ needs['tag-generate-query'].outputs.new_tag }}

  notify-query:
    if: ${{ always() }}
    needs: [ci-blog_query, prod-build-query, tag-generate-query, vercel-deploy-query, tag-push-query]
    uses: ./.github/workflows/reusable-telegram-deploy-notify.yml
    with:
      project-name: 'FSO BlogApp Frontend (React + TanStack Query + MUI)'
      should-deploy: ${{ needs.ci-blog_query.outputs.should_deploy }}
      new-tag: ${{ needs['tag-generate-query'].outputs.new_tag }}
      statuses-text: |
        Job statuses:
        • CI-checks:     ${{ needs.ci-blog_query.result }}
        • Prod build:    ${{ needs['prod-build-query'].result }}
        • Tag-generate:  ${{ needs['tag-generate-query'].result }}
        • Vercel deploy: ${{ needs['vercel-deploy-query'].result }}
        • Tag-push:      ${{ needs['tag-push-query'].result }}
    secrets:
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}