name: Deployment Pipeline For Part 11 of FSO Course Task pokedex

on: 
  push:
    branches:
      - main
    paths:
      - 'Part-11/full-stack-open-pokedex/**'
  workflow_dispatch:

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '16.16.0'
      - name: Install dependencies 
        run: npm install  

      - name: Check style
        run: npm run eslint
