name: Reusable Health Check

on:
  workflow_call:
    inputs:
      url:
        required: true
        type: string

jobs:
  health-check:
    runs-on: ubuntu-latest
    steps:
      - name: Health check
        run: |
          echo "Waiting for app to become healthy..."
          sleep 10
          curl -f ${{ inputs.url }}