name: Reusable Fly Deploy

on:
  workflow_call:
    inputs:
      should-deploy:
        required: true
        type: string
      working-directory:
        required: true
        type: string
      image-label:
        required: true
        type: string
      
    secrets:
      FLY_DEPLOY_TOKEN:
        required: true

jobs:
  fly-deploy:
    runs-on: ubuntu-latest
    if: ${{ inputs.should-deploy == 'true' }}
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --image-label ${{ inputs.image-label }}
        env:
          FLY_DEPLOY_TOKEN: ${{ secrets.FLY_DEPLOY_TOKEN }}

      - name: Health check
        run: |
          echo "Waiting for app to become healthy..."
          sleep 10
          curl -f https://blogs-fso.fly.dev/health