name: Reusable Tag Push

on:
  workflow_call:
    inputs:
      should-deploy:
        required: true
        type: string
      tag-to-push:
        required: true
        type: string

jobs:
  tag-push:
    runs-on: ubuntu-latest
    if: ${{ inputs.should-deploy == 'true' }}
    steps:
      - uses: actions/checkout@v4
      - name: Push tag
        uses: anothrNick/github-tag-action@4ed44965e0db8dab2b466a16da04aec3cc312fd8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          CUSTOM_TAG: ${{ inputs.tag-to-push }}