name: Reusable Telegram Deploy Notify

on:
  workflow_call:
    inputs:
      should-deploy:
        required: true
        type: string
      ci-result:
        required: true
        type: string
      tag-result:
        required: true
        type: string
      deploy-result:
        required: true
        type: string
      health-result:
        required: false
        type: string
        default: ""
      new-tag:
        required: true
        type: string

jobs:
  notify:
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Notify Telegram Success
        if: ${{ inputs.should-deploy == 'true' && inputs.deploy-result == 'success' }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            ✅ Deploy succeeded
            Tag `${{ inputs.new-tag }}` deployed

            Statuses:
            • CI-checks:   ${{ inputs.ci-result }}
            • Tag-push:    ${{ inputs.tag-result }}
            • Fly deploy:  ${{ inputs.deploy-result }}
            • Health (/ready): ${{ inputs.health-result }}

            👉 View run: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

      - name: Notify Telegram Failure
        if: ${{ inputs.ci-result == 'failure' || inputs.tag-result == 'failure' || inputs.deploy-result == 'failure' || inputs.health-result == 'failure' }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            ❌ Build/Deploy failed

            • Repository: ${{ github.repository }}
            • Workflow:   ${{ github.workflow }}
            • Event:      ${{ github.event_name }}
            • Commit:     ${{ github.sha }}
            • Actor:      ${{ github.actor }}

            Job statuses:
            • CI-checks:      ${{ inputs.ci-result }}
            • Tag-push:       ${{ inputs.tag-result }}
            • Fly deploy:     ${{ inputs.deploy-result }}
            • Health (/ready): ${{ inputs.health-result }}

            👉 View run: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}