name: Reusable Tag Generate

on:
  workflow_call:
    inputs:
      should-deploy:
        required: true
        type: string
      tag-prefix:
        required: false
        type: string
        default: ""
    outputs:
      new_tag:
        description: "Next git tag (not pushed)"
        value: ${{ jobs.tag-generate.outputs.new_tag }}

jobs:
  tag-generate:
    runs-on: ubuntu-latest
    if: ${{ inputs.should-deploy == 'true' }}
    outputs:
      new_tag: ${{ steps.tag.outputs.new_tag }}
    steps:
      - uses: actions/checkout@v4
      - name: Generate next tag (dry-run)
        id: tag
        uses: anothrNick/github-tag-action@4ed44965e0db8dab2b466a16da04aec3cc312fd8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          TAG_PREFIX: ${{ inputs.tag-prefix }}
          DRY_RUN: true