name: Reusable Telegram Deploy Notify

on:
  workflow_call:
    inputs:
      project-name:
        required: true
        type: string
      should-deploy:
        required: true
        type: string
      statuses-text:
        required: true
        type: string
      new-tag:
        required: true
        type: string
      is-success:
        required: true
        type: string
    secrets:
      TELEGRAM_CHAT_ID:
        required: true
      TELEGRAM_BOT_TOKEN:
        required: true

jobs:
  notify:
    runs-on: ubuntu-latest
    # run only if deploy was intended
    if: ${{ inputs.should-deploy == 'true' }}
    steps:
      - name: Notify Telegram Success
        if: ${{ inputs.is-success == 'true' }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: html
          message: |
            🚀 <b>${{ inputs.project-name }}</b>

            ✅ Deploy succeeded
            Tag <code>${{ inputs.new-tag }}</code> deployed

            ${{ inputs.statuses-text }}

            👉 <a href="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}">View run</a>

      - name: Notify Telegram Failure
        if: ${{ inputs.is-success != 'true' }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: html
          message: |
            🚨 <b>${{ inputs.project-name }}</b>

            ❌ Build/Deploy failed

            • Repository: ${{ github.repository }}
            • Workflow:   ${{ github.workflow }}
            • Event:      ${{ github.event_name }}
            • Commit:     ${{ github.sha }}
            • Actor:      ${{ github.actor }}

            ${{ inputs.statuses-text }}

            👉 <a href="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}">View run</a>