name: Reusable Tag Release

on:
  workflow_call:
    inputs:
      should-deploy:
        required: true
        type: string
      custom-tag:
        required: false
        type: string
        default: ""
    outputs:
      new_tag:
        description: "Created git tag"
        value: ${{ jobs.tag-release.outputs.new_tag }}

jobs:
  tag-release:
    runs-on: ubuntu-latest
    if: ${{ inputs.should-deploy == 'true' }}
    outputs:
      new_tag: ${{ steps.tag.outputs.new_tag }}
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        id: tag
        uses: anothrNick/github-tag-action@e528bc2b9628971ce0e6f823f3052d1dcd9d512c
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          WITH_V: true
          CUSTOM_TAG: ${{ inputs.custom-tag }}
